[[redirects]]
    from = "predelegate"
    to = "https://res.cloudinary.com/celc/image/upload/v1663785282/pre-delegate-form/package/Pre_Delegate_Package_EN_wbiscj.pdf"
    status = 200

[[redirects]]
    from = "predelegues"
    to = "https://res.cloudinary.com/celc/image/upload/v1663785273/pre-delegate-form/package/Paquet_De_Pre_delegues_FR_kkqwdn.pdf"
    status = 200

[[redirects]]
    from = "careerfairpackage"
    to = "https://celcassets.cfes.ca/packages/Career_Fair_Package_EN.pdf"
    status = 200

[[redirects]]
    from = "schedule"
    to = "https://docs.google.com/spreadsheets/d/1XVJHUL8Y3dbs3iR5aHOk0oQDtJvMDaCUvgWv3txxZTQ/view#gid=220569605"
    status = 301

[[redirects]]
    from = "programme"
    to = "https://docs.google.com/spreadsheets/d/1XVJHUL8Y3dbs3iR5aHOk0oQDtJvMDaCUvgWv3txxZTQ/view#gid=2007036342"
    status = 301 

[[redirects]]
    from = "delegate"
    to = "https://celcassets.cfes.ca/packages/Delegate_Package_EN.pdf"
    status = 301

[[redirects]]
    from = "delegues"
    to = "https://celcassets.cfes.ca/packages/Paquet_De_delegues_FR.pdf"
    status = 301


[[redirects]]
    from = "programming"
    to = "https://celcassets.cfes.ca/packages/Programming_Package_EN.pdf"
    status = 301

[[redirects]]
    from = "programme"
    to = "https://celcassets.cfes.ca/packages/Paquetdeprogramme_FR.pdf"
    status = 301

[[redirects]]
    from = "irc"
    to = "https://forms.gle/oGqU5rTumKY5MrLy8"
    status = 301

[[redirects]]
    from = "casecomp"
    to = "https://drive.google.com/drive/folders/1Nu57SIeJB_GxgAWsCCA47Texk-zSaibf?usp=sharing"
    status = 301

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200