[[redirects]]
    from = "predelegate"
    to = "https://drive.google.com/file/d/18NZx8Pm9NFpxOkploIQx0r49hFv6IjBs/view?usp=share_link"
    status = 301

[[redirects]]
    from = "predelegues"
    to = "https://drive.google.com/file/d/19L64-TfN9a9nAdheLT-yD4eoHVdjdqnT/view?usp=share_link"
    status = 301

[[redirects]]
    from = "careerfairpackage"
    to = "https://drive.google.com/file/d/1HCAskd__DMZn35D3lb8JI4snRvUBXcPL/view?usp=share_link"
    status = 301

[[redirects]]
    from = "schedule"
    to = "https://docs.google.com/spreadsheets/d/1XVJHUL8Y3dbs3iR5aHOk0oQDtJvMDaCUvgWv3txxZTQ/view#gid=220569605"
    status = 301

[[redirects]]
    from = "programme"
    to = "https://docs.google.com/spreadsheets/d/1XVJHUL8Y3dbs3iR5aHOk0oQDtJvMDaCUvgWv3txxZTQ/view#gid=2007036342"
    status = 301 

[[redirects]]
    from = "delegate"
    to = "https://drive.google.com/file/d/1hUHZVxigji6YVntgpHme0llzH20_2728/view?usp=share_link"
    status = 301

[[redirects]]
    from = "delegues"
    to = "https://drive.google.com/file/d/1tOe3_S9k470qWcUT0Kurpfn7rwshvtZ8/view?usp=share_link"
    status = 301


[[redirects]]
    from = "programming"
    to = "https://drive.google.com/file/d/1hP7feCM_i9Fx8hkEOfyOAEuW5SMqQptp/view?usp=share_link"
    status = 301

[[redirects]]
    from = "paquetdeprogramme"
    to = "https://drive.google.com/file/d/1UPmaEWfVxlkHLk3AYWfC5dRBOEA3RsfX/view?usp=share_link"
    status = 301

[[redirects]]
    from = "irc"
    to = "https://forms.gle/oGqU5rTumKY5MrLy8"
    status = 301

[[redirects]]
    from = "casecomp"
    to = "https://drive.google.com/drive/folders/1Nu57SIeJB_GxgAWsCCA47Texk-zSaibf?usp=sharing"
    status = 301

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200